id:
  original_name: "id"
  type: "categorical"
  is_primary_key: true
  label: "ID"
species:
  original_name: "species"
  type: "categorical"
  label: "Species"
amr_class:
  original_name: "amr_class"
  type: "categorical"
  label: "AMR Class"
collection_date:
  original_name: "collection_date"
  type: "categorical"
  label: "Collection Date"
value:
  original_name: "value"
  type: "categorical"
  label: "Value"
