sample_id:
  original_name: sample_id
  type: categorical
  label: Sample Id
mic_id:
  original_name: mic_id
  type: categorical
  label: Mic Id
breakpoint:
  original_name: breakpoint
  type: categorical
  label: Breakpoint
predicted_phenotype:
  original_name: phenotype
  type: categorical
  label: Phenotype
