Gene_name:
  original_name: Gene_name
  type: categorical
  label: Gene Name
Location:
  original_name: Location
  type: categorical
  label: Location
Name_plasmid:
  original_name: Name_plasmid
  type: categorical
  label: Name Plasmid
VirulenceFinder:
  original_name: VirulenceFinder
  type: categorical
  label: Virulencefinder
