sample_id:
  original_name: sample_id
  type: categorical
  label: Sample Id
host_animal_common:
  original_name: host_animal_common
  type: categorical
  label: Host Animal Common
specimen_source_tissue:
  original_name: specimen_source_tissue
  type: categorical
  label: Specimen Source Tissue
animal_infection_site_uti:
  original_name: animal_infection_site_uti
  type: categorical
  label: Animal Infection Site Uti
