spec:
  target_dataset: AMR_Profile_Joint
  theme: theme_light
  layers:
  - name: geom_bar
    params: {}
  - name: position_dodge
    params: {}
  - name: scale_x_discrete
    params: {}
  - name: labs
    params:
      title: Multi-Resistance by Country
      fill: Multiresistant
      x: Year
  mapping:
    x: Year
    fill: Multiresistant
    facet_by: Country
