"""Gate tests for TL-BOOTSTRAP-FIX-1 — ManifestBootstrapper correctness."""
import pytest
import yaml
from pathlib import Path


@pytest.fixture
def minimal_tsv(tmp_path):
    """Single-column TSV with a sample_id primary key."""
    tsv = tmp_path / "samples.tsv"
    tsv.write_text("sample_id\tspecies\ncnr001\tE. coli\ncnr002\tS. aureus\n")
    return tsv


@pytest.fixture
def meta_tsv(tmp_path):
    """Separate metadata TSV."""
    tsv = tmp_path / "metadata.tsv"
    tsv.write_text("sample_id\tcollection_year\ncnr001\t2023\ncnr002\t2024\n")
    return tsv


def _load_yaml(path):
    """Load YAML without resolving !include tags — inspect raw structure."""
    with open(path) as f:
        return yaml.safe_load(f)


class TestBootstrapperBugFixes:
    """Tests that cover the three bugs fixed by TL-BOOTSTRAP-FIX-1."""

    def test_uses_analysis_groups_not_plotting(self, minimal_tsv, tmp_path):
        from test_lab.bootstrapper import ManifestBootstrapper
        bs = ManifestBootstrapper()
        master = bs.bootstrap([minimal_tsv], "test_proj", tmp_path)
        raw = master.read_text()
        assert "analysis_groups" in raw, "master manifest must contain 'analysis_groups'"
        assert "plotting" not in raw, "legacy 'plotting' key must not appear"

    def test_no_metadata_schema_by_default(self, minimal_tsv, tmp_path):
        from test_lab.bootstrapper import ManifestBootstrapper
        bs = ManifestBootstrapper()
        master = bs.bootstrap([minimal_tsv], "test_proj", tmp_path)
        raw = master.read_text()
        # Check for the YAML key form (with colon) to avoid matching substrings
        # in tmp_path directory names generated by pytest.
        assert "metadata_schema:" not in raw, (
            "metadata_schema key must NOT appear when no metadata_path was supplied"
        )

    def test_metadata_schema_present_when_supplied(self, minimal_tsv, meta_tsv, tmp_path):
        from test_lab.bootstrapper import ManifestBootstrapper
        bs = ManifestBootstrapper()
        master = bs.bootstrap([minimal_tsv], "test_proj", tmp_path, metadata_path=meta_tsv)
        raw = master.read_text()
        assert "metadata_schema" in raw

    def test_join_manifests_stub_present(self, minimal_tsv, tmp_path):
        from test_lab.bootstrapper import ManifestBootstrapper
        bs = ManifestBootstrapper()
        master = bs.bootstrap([minimal_tsv], "test_proj", tmp_path)
        raw = master.read_text()
        assert "join_manifests" in raw

    def test_wrangling_fragment_is_tiered(self, minimal_tsv, tmp_path):
        from test_lab.bootstrapper import ManifestBootstrapper
        bs = ManifestBootstrapper()
        bs.bootstrap([minimal_tsv], "test_proj", tmp_path)
        frag = tmp_path / "test_proj" / "test_proj" / "samples_wrangling.yaml"
        assert frag.exists(), f"Wrangling fragment not found at {frag}"
        content = frag.read_text()
        assert "tier1" in content, "wrangling fragment must have 'tier1' key"
        assert "tier2" in content, "wrangling fragment must have 'tier2' key"


class TestIdCleaningRecipes:
    """Tests for the id_cleaning_recipes parameter."""

    def test_cleaning_steps_injected_into_tier1(self, minimal_tsv, tmp_path):
        from test_lab.bootstrapper import ManifestBootstrapper
        recipes = {
            "samples": [
                {"action": "strip_whitespace", "columns": ["sample_id"]},
            ]
        }
        bs = ManifestBootstrapper()
        bs.bootstrap([minimal_tsv], "test_proj", tmp_path, id_cleaning_recipes=recipes)
        frag = tmp_path / "test_proj" / "test_proj" / "samples_wrangling.yaml"
        data = yaml.safe_load(frag.read_text().lstrip("# Candidate PK:").split("\n", 1)[-1])
        # The wrangling fragment may have PK comment line; parse YAML after it
        content = frag.read_text()
        # Strip comment lines before parsing
        yaml_lines = [l for l in content.splitlines() if not l.startswith("#")]
        data = yaml.safe_load("\n".join(yaml_lines))
        assert len(data["tier1"]) == 1
        assert data["tier1"][0]["action"] == "strip_whitespace"

    def test_no_cleaning_recipes_produces_empty_tier1(self, minimal_tsv, tmp_path):
        from test_lab.bootstrapper import ManifestBootstrapper
        bs = ManifestBootstrapper()
        bs.bootstrap([minimal_tsv], "test_proj", tmp_path)
        frag = tmp_path / "test_proj" / "test_proj" / "samples_wrangling.yaml"
        yaml_lines = [l for l in frag.read_text().splitlines() if not l.startswith("#")]
        data = yaml.safe_load("\n".join(yaml_lines))
        assert data["tier1"] == [] or data["tier1"] is None


class TestOutputStructure:
    """Verify the generated file tree and master manifest keys."""

    def test_master_manifest_id_matches_project(self, minimal_tsv, tmp_path):
        from test_lab.bootstrapper import ManifestBootstrapper
        bs = ManifestBootstrapper()
        master = bs.bootstrap([minimal_tsv], "my_pipeline", tmp_path)
        assert master.name == "my_pipeline.yaml"
        assert master.parent.name == "my_pipeline"

    def test_fragment_files_created(self, minimal_tsv, tmp_path):
        from test_lab.bootstrapper import ManifestBootstrapper
        bs = ManifestBootstrapper()
        bs.bootstrap([minimal_tsv], "test_proj", tmp_path)
        frags = tmp_path / "test_proj" / "test_proj"
        assert (frags / "samples_input_fields.yaml").exists()
        assert (frags / "samples_wrangling.yaml").exists()
        assert (frags / "samples_output_fields.yaml").exists()

    def test_input_fields_infers_sample_id_as_pk(self, minimal_tsv, tmp_path):
        from test_lab.bootstrapper import ManifestBootstrapper
        bs = ManifestBootstrapper()
        bs.bootstrap([minimal_tsv], "test_proj", tmp_path)
        frag = tmp_path / "test_proj" / "test_proj" / "samples_input_fields.yaml"
        data = yaml.safe_load(frag.read_text())
        assert data["sample_id"]["is_primary_key"] is True
