output_fields:
  sample_id:
    type: numeric
    label: Sample ID
    is_primary_key: true
    original_name: sample_id
  source:
    type: categorical
    label: Biological Source
    original_name: source
  year:
    type: numeric
    label: Collection Year
    original_name: year
  country:
    type: categorical
    label: Origin Country
    original_name: country
  sequence_type:
    type: categorical
    label: MLST Sequence Type
    original_name: sequence_type
  serotype:
    type: categorical
    label: Serotype
    original_name: serotype
  Selected_Virulence_Genes:
    type: categorical
    label: Gene (VirulenceFinder)
    original_name: Selected_Virulence_Genes
  VF_protein:
    type: categorical
    label: Protein (VirulenceFinder)
    original_name: VF_protein
  gene:
    type: categorical
    label: AMR Gene
    original_name: gene
  status:
    type: categorical
    label: Phenotype Status
    original_name: status
  phenotype:
    type: categorical
    label: AMR Class / Phenotype
    original_name: phenotype
