"""
Anonymiser — reversible ID anonymisation for TEST_LAB (headless, Shiny-free).

Replaces real IDs with synthetic equivalents. Same original_id always maps to
the same anon_id, preserving join validity across related files.

Three ID patterns: sequential (ANON_0001), hash (sha256 hex prefix), or a
custom Python format string such as "SUBJ_{:05d}".

Outputs:
  anonymised_<stem>.tsv        — data with replaced IDs; personal cols stripped
  mapping_<id_column>.tsv      — original_id | anon_id | (personal cols)
  anonymisation_config.yaml    — audit record (NOT a pipeline manifest)
"""

from __future__ import annotations

import hashlib
import re
from datetime import date
from pathlib import Path
from typing import Any

import polars as pl
import yaml

# @deps
# provides: Anonymiser class (anonymise, anonymise_batch, build_deanon_recipe)
# consumes: polars, hashlib, yaml, datetime, pathlib (stdlib/third-party)
# consumed_by: libs/test_lab/tests/test_anonymiser.py
#              app/handlers/test_lab_handlers.py (TL-UI-ANON-1 — not yet built)
# @end_deps

_MANDATORY_HEADER = (
    "# NOT a pipeline manifest. NOT processed by the SPARMVET data engine.\n"
    "# Generated by Anonymiser. For audit reference only.\n"
)

_HASH_PREFIX_LEN = 8


def _make_sequential_id(i: int, prefix: str) -> str:
    return f"{prefix}_{i:04d}"


def _make_hash_id(original: str, prefix: str) -> str:
    digest = hashlib.sha256(original.encode()).hexdigest()[:_HASH_PREFIX_LEN].upper()
    return f"{prefix}_{digest}"


def _make_custom_id(i: int, original: str, fmt: str) -> str:
    """Apply a Python format string. Supports positional {i} and named {original}."""
    if "{original" in fmt:
        return fmt.format(original=original, i=i)
    return fmt.format(i)


class Anonymiser:
    """Reversible ID anonymiser for TEST_LAB.

    Usage::

        anon = Anonymiser()
        anon_df, mapping_df = anon.anonymise(
            "metadata.tsv",
            id_column="sample_id",
            personal_columns=["name", "address"],
            pattern="sequential",
            out_dir="/tmp/anon_output",
        )
    """

    MANDATORY_HEADER = _MANDATORY_HEADER

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def anonymise(
        self,
        filepath: str | Path,
        id_column: str,
        personal_columns: list[str] | None = None,
        pattern: str = "sequential",
        prefix: str = "ANON",
        existing_mapping: dict[str, str] | None = None,
        out_dir: str | Path | None = None,
    ) -> tuple[pl.DataFrame, pl.DataFrame]:
        """Anonymise a single TSV/CSV file.

        Returns (anonymised_df, mapping_df). Writes files when out_dir is given.

        Parameters
        ----------
        filepath:
            Source file (TSV or CSV).
        id_column:
            Column containing original IDs to replace.
        personal_columns:
            Columns to strip from anonymised output and add to mapping TSV.
        pattern:
            "sequential" | "hash" | custom Python format string (e.g. "SUBJ_{:05d}").
        prefix:
            Prefix for sequential/hash patterns (default: "ANON").
        existing_mapping:
            Pre-built {original_id: anon_id} dict — used by anonymise_batch for
            cross-file consistency. New IDs are added to this mapping in place.
        out_dir:
            If set, writes anonymised TSV, mapping TSV, and config YAML here.
        """
        filepath = Path(filepath)
        personal_columns = list(personal_columns or [])
        df = self._read_file(filepath)
        self._validate_columns(df, id_column, personal_columns)

        mapping = existing_mapping if existing_mapping is not None else {}
        mapping = self._extend_mapping(df[id_column].to_list(), mapping, pattern, prefix)

        anon_col = f"anon_{id_column}"
        anon_df = self._apply_mapping(df, id_column, anon_col, mapping, personal_columns)
        mapping_df = self._build_mapping_df(mapping, id_column, df, personal_columns)

        if out_dir is not None:
            out_dir = Path(out_dir)
            out_dir.mkdir(parents=True, exist_ok=True)
            anon_path = out_dir / f"anonymised_{filepath.stem}.tsv"
            mapping_path = out_dir / f"mapping_{id_column}.tsv"
            config_path = out_dir / "anonymisation_config.yaml"

            anon_df.write_csv(str(anon_path), separator="\t")
            mapping_df.write_csv(str(mapping_path), separator="\t")
            self._write_config(
                config_path,
                id_column=id_column,
                personal_columns=personal_columns,
                pattern=pattern,
                prefix=prefix,
                files=[filepath.name],
                mapping_file=mapping_path.name,
            )

        return anon_df, mapping_df

    def anonymise_batch(
        self,
        filepaths: list[str | Path],
        id_column: str,
        personal_columns: list[str] | None = None,
        pattern: str = "sequential",
        prefix: str = "ANON",
        out_dir: str | Path | None = None,
    ) -> dict[str, Any]:
        """Anonymise multiple related files with a shared ID mapping.

        Same original_id always maps to the same anon_id across all files,
        preserving join validity post-anonymisation.

        Returns a dict with keys:
          "mapping"        → pl.DataFrame (combined mapping)
          "<stem>.tsv"     → pl.DataFrame (anonymised data per file)
          "config"         → dict (audit config)
        """
        filepaths = [Path(p) for p in filepaths]
        personal_columns = list(personal_columns or [])

        # Collect all unique original IDs across every file first, then build
        # a single mapping so the same ID always gets the same anon replacement.
        all_ids: list[str] = []
        frames: dict[str, pl.DataFrame] = {}
        for fp in filepaths:
            df = self._read_file(fp)
            self._validate_columns(df, id_column, personal_columns)
            frames[fp.stem] = df
            all_ids.extend(df[id_column].cast(pl.Utf8).to_list())

        unique_ids = list(dict.fromkeys(all_ids))  # stable-dedup preserving first-seen order
        mapping: dict[str, str] = {}
        self._extend_mapping(unique_ids, mapping, pattern, prefix)

        results: dict[str, Any] = {}
        personal_dfs: list[pl.DataFrame] = []

        for fp in filepaths:
            df = frames[fp.stem]
            anon_col = f"anon_{id_column}"
            anon_df = self._apply_mapping(df, id_column, anon_col, mapping, personal_columns)
            results[f"{fp.stem}.tsv"] = anon_df
            personal_dfs.append(df)

            if out_dir is not None:
                out_path = Path(out_dir)
                out_path.mkdir(parents=True, exist_ok=True)
                anon_df.write_csv(str(out_path / f"anonymised_{fp.stem}.tsv"), separator="\t")

        # Combined mapping using the first file's personal column data (primary file)
        mapping_df = self._build_mapping_df(
            mapping, id_column, personal_dfs[0], personal_columns
        )
        results["mapping"] = mapping_df

        config = {
            "run_date": str(date.today()),
            "id_column": id_column,
            "personal_columns": personal_columns,
            "pattern": pattern,
            "prefix": prefix,
            "files_anonymised": [fp.name for fp in filepaths],
            "mapping_file": f"mapping_{id_column}.tsv",
        }
        results["config"] = config

        if out_dir is not None:
            out_path = Path(out_dir)
            mapping_path = out_path / f"mapping_{id_column}.tsv"
            mapping_df.write_csv(str(mapping_path), separator="\t")
            self._write_config(
                out_path / "anonymisation_config.yaml",
                id_column=id_column,
                personal_columns=personal_columns,
                pattern=pattern,
                prefix=prefix,
                files=[fp.name for fp in filepaths],
                mapping_file=mapping_path.name,
            )

        return results

    def build_deanon_recipe(self, id_column: str, mapping_filename: str) -> str:
        """Return a YAML snippet for a BLUEPRINT join recipe to restore original IDs.

        Paste this into a tier2 wrangling block in BLUEPRINT to de-anonymise results
        by joining the anonymised dataset with the mapping TSV.
        """
        anon_col = f"anon_{id_column}"
        snippet = {
            "action": "join",
            "right_ingredient": "mapping_schema",
            "left_on": anon_col,
            "right_on": anon_col,
            "how": "inner",
            "_comment": (
                f"Join anonymised data with {mapping_filename} on {anon_col} "
                f"to restore original {id_column}."
            ),
        }
        return yaml.dump([snippet], default_flow_style=False, allow_unicode=True)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _read_file(filepath: Path) -> pl.DataFrame:
        sep = "\t" if filepath.suffix.lower() == ".tsv" else ","
        return pl.read_csv(str(filepath), separator=sep, infer_schema_length=0)

    @staticmethod
    def _validate_columns(
        df: pl.DataFrame,
        id_column: str,
        personal_columns: list[str],
    ) -> None:
        # Only id_column is required; personal_columns are stripped where present.
        if id_column not in df.columns:
            raise ValueError(f"ID column not found in source: {id_column!r}")

    def _extend_mapping(
        self,
        ids: list[str],
        mapping: dict[str, str],
        pattern: str,
        prefix: str,
    ) -> dict[str, str]:
        """Add any IDs not yet in mapping. Returns the same dict (mutated in place)."""
        counter = len(mapping)
        for original in ids:
            original_str = str(original)
            if original_str not in mapping:
                counter += 1
                mapping[original_str] = self._generate_id(
                    counter, original_str, pattern, prefix
                )
        return mapping

    @staticmethod
    def _generate_id(i: int, original: str, pattern: str, prefix: str) -> str:
        if pattern == "sequential":
            return _make_sequential_id(i, prefix)
        if pattern == "hash":
            return _make_hash_id(original, prefix)
        # custom format string
        return _make_custom_id(i, original, pattern)

    @staticmethod
    def _apply_mapping(
        df: pl.DataFrame,
        id_column: str,
        anon_col: str,
        mapping: dict[str, str],
        personal_columns: list[str],
    ) -> pl.DataFrame:
        ids_str = df[id_column].cast(pl.Utf8).to_list()
        anon_ids = [mapping[v] for v in ids_str]
        # personal_columns are stripped where present; files without them are unaffected
        strip = set(personal_columns) & set(df.columns)
        keep_cols = [c for c in df.columns if c not in strip and c != id_column]
        return df.select(keep_cols).with_columns(
            pl.Series(anon_col, anon_ids)
        ).select([anon_col] + keep_cols)

    @staticmethod
    def _build_mapping_df(
        mapping: dict[str, str],
        id_column: str,
        source_df: pl.DataFrame,
        personal_columns: list[str],
    ) -> pl.DataFrame:
        anon_col = f"anon_{id_column}"
        orig_col = f"original_{id_column}"
        orig_ids = list(mapping.keys())
        anon_ids = [mapping[k] for k in orig_ids]
        base = pl.DataFrame(
            {orig_col: orig_ids, anon_col: anon_ids}
        )
        if not personal_columns:
            return base
        # Pull personal columns from source_df by matching on original id values
        lookup = (
            source_df
            .select([id_column] + personal_columns)
            .rename({id_column: orig_col})
            .unique(subset=[orig_col])
        )
        return base.join(lookup, on=orig_col, how="left")

    def _write_config(
        self,
        path: Path,
        *,
        id_column: str,
        personal_columns: list[str],
        pattern: str,
        prefix: str,
        files: list[str],
        mapping_file: str,
    ) -> None:
        payload = {
            "anonymisation_config": {
                "run_date": str(date.today()),
                "id_column": id_column,
                "personal_columns": personal_columns,
                "pattern": pattern,
                "prefix": prefix,
                "files_anonymised": files,
                "mapping_file": mapping_file,
            }
        }
        path.write_text(
            self.MANDATORY_HEADER + yaml.dump(payload, default_flow_style=False, allow_unicode=True)
        )
