# @deps
# provides: AquaSynthesizer class (propose_config, generate, save_config, load_config, list_scenarios)
#           module helpers: clean_header, generate_fake_column, introduce_missing_values
# consumes: polars, numpy, random, re, pathlib, datetime, argparse, yaml, typing (stdlib/third-party)
# consumed_by: libs/test_lab/tests/test_synthesizer.py
#              libs/test_lab/tests/debug_sdk.py (legacy synthesize() API — needs update to new two-step flow)
#              assets/scripts/generate_demo_data.py
# @end_deps
#!/usr/bin/env python3
import argparse
import random
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Union

import numpy as np
import polars as pl
import yaml


_PK_SUFFIXES = ("_id", "_pk", "_key", "_code", "_num", "_no")
_PK_EXACT = {"id", "pk", "key", "accession", "barcode", "sample"}
_CARDINALITY_THRESHOLD = 15
_MALFORMED_STRINGS = ["2O22", "99.99.99", "N/A", "??", "---", "ERR!"]


def _is_pk_name(col: str) -> bool:
    lo = col.lower()
    return lo in _PK_EXACT or any(lo.endswith(s) for s in _PK_SUFFIXES) or lo.startswith("id_")


class AquaSynthesizer:
    """
    Two-step synthetic data generator.

    Flow:
        s = AquaSynthesizer()
        cfg = s.propose_config(source_tsv, n_rows=100, mode="stress_test")
        cfg["error_injection"]["missing_values"] = {"rate": 0.10, "columns": ["species"]}
        df = s.generate(cfg, out_path=Path("output.tsv"), seed=42)
        s.save_config(cfg, "my_scenario", Path("libs/test_lab/scenarios/"))
        loaded = s.load_config("my_scenario", Path("libs/test_lab/scenarios/"))
    """

    MANDATORY_HEADER = (
        "# NOT a pipeline manifest. NOT processed by the SPARMVET data engine.\n"
        "# Generated by AquaSynthesizer. Load with AquaSynthesizer.load_config() only.\n"
    )

    def propose_config(
        self,
        source: Union[Path, str, List[str]],
        n_rows: int = 50,
        mode: str = "demo",
    ) -> dict:
        """Inspect source (TSV path or column name list) and return a generation config dict."""
        if isinstance(source, (str, Path)):
            columns = self._infer_from_tsv(Path(source))
        else:
            columns = self._infer_from_names(source)

        pk_col = next((c["name"] for c in columns if c.get("is_pk")), None)
        return {
            "mode": mode,
            "n_rows": n_rows,
            "primary_key_column": pk_col,
            "columns": columns,
            "error_injection": {
                "missing_values": {"rate": 0.0, "columns": []},
                "wrong_type": {"rate": 0.0, "columns": []},
                "duplicate_ids": {"rate": 0.0},
                "pk_mismatches": {"rate": 0.0},
                "schema_errors": {"rate": 0.0},
                "malformed_fields": {"rate": 0.0, "columns": []},
            },
        }

    def generate(
        self,
        config: dict,
        out_path: Optional[Path] = None,
        seed: Optional[int] = None,
    ) -> pl.DataFrame:
        """Generate synthetic data from a config dict. Returns a Polars DataFrame."""
        if seed is not None:
            np.random.seed(seed)
            random.seed(seed)

        n_rows = config["n_rows"]
        columns = config["columns"]
        mode = config.get("mode", "demo")
        pk_col = config.get("primary_key_column")

        series_list = [self._gen_column(spec, n_rows) for spec in columns]
        df = pl.DataFrame(series_list)

        if mode == "stress_test":
            df = self._apply_error_injection(df, config, pk_col)

        if out_path is not None:
            out_path = Path(out_path)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            df.write_csv(out_path, separator="\t")

        return df

    def save_config(self, config: dict, name: str, scenarios_dir: Path) -> Path:
        """Archive a config dict as a named YAML scenario with mandatory header."""
        scenarios_dir = Path(scenarios_dir)
        scenarios_dir.mkdir(parents=True, exist_ok=True)
        path = scenarios_dir / f"{name}.yaml"
        wrapped = {"synthetic_data_config": {**config, "scenario": {"name": name}}}
        content = self.MANDATORY_HEADER + yaml.dump(wrapped, sort_keys=False, allow_unicode=True)
        path.write_text(content)
        return path

    def load_config(self, name: str, scenarios_dir: Path) -> dict:
        """Load a named scenario YAML. Returns the config dict (scenario metadata stripped)."""
        path = Path(scenarios_dir) / f"{name}.yaml"
        data = yaml.safe_load(path.read_text())
        inner = dict(data["synthetic_data_config"])
        inner.pop("scenario", None)
        return inner

    def list_scenarios(self, scenarios_dir: Path) -> list:
        """List scenario names in scenarios_dir. Returns [] if directory does not exist."""
        p = Path(scenarios_dir)
        if not p.exists():
            return []
        return sorted(f.stem for f in p.glob("*.yaml"))

    # ------------------------------------------------------------------
    # Internal: column inference
    # ------------------------------------------------------------------

    def _infer_from_tsv(self, path: Path) -> List[dict]:
        df = pl.read_csv(path, separator="\t", n_rows=100)
        columns = []
        for col in df.columns:
            series = df[col]
            dtype = series.dtype
            n_unique = series.n_unique()
            n_loaded = len(df)
            is_unique = (n_unique == n_loaded) and n_loaded > 1
            is_pk = is_unique and _is_pk_name(col)
            spec: dict = {"name": col}

            if is_pk:
                spec.update({"dtype": "string", "is_pk": True, "pattern": f"{col}_{{i:04d}}"})
            elif dtype in (pl.Int8, pl.Int16, pl.Int32, pl.Int64,
                           pl.UInt8, pl.UInt16, pl.UInt32, pl.UInt64):
                vals = series.drop_nulls()
                spec.update({
                    "dtype": "integer",
                    "min": int(vals.min() if len(vals) else 0),
                    "max": int(vals.max() if len(vals) else 100),
                })
            elif dtype in (pl.Float32, pl.Float64):
                vals = series.drop_nulls()
                mn = float(vals.min()) if len(vals) else 0.0
                mx = float(vals.max()) if len(vals) else 1.0
                if mn == mx:
                    mx = mn + 1.0
                spec.update({"dtype": "float", "min": round(mn, 4), "max": round(mx, 4)})
            elif dtype == pl.Boolean:
                spec.update({"dtype": "boolean"})
            elif n_unique <= _CARDINALITY_THRESHOLD:
                vals_list = sorted(str(v) for v in series.drop_nulls().unique().to_list())
                spec.update({"dtype": "categorical", "values": vals_list})
            else:
                spec.update({"dtype": "string"})

            columns.append(spec)
        return columns

    def _infer_from_names(self, names: List[str]) -> List[dict]:
        columns = []
        for name in names:
            if _is_pk_name(name):
                columns.append({
                    "name": name, "dtype": "string", "is_pk": True,
                    "pattern": f"{name}_{{i:04d}}",
                })
            else:
                columns.append({
                    "name": name, "dtype": "categorical",
                    "values": ["value_A", "value_B", "value_C"],
                })
        return columns

    # ------------------------------------------------------------------
    # Internal: column generation
    # ------------------------------------------------------------------

    def _gen_column(self, spec: dict, n_rows: int) -> pl.Series:
        name = spec["name"]
        dtype = spec.get("dtype", "string")

        if spec.get("is_pk") and spec.get("pattern"):
            pattern = spec["pattern"]
            return pl.Series(name, [pattern.format(i=i) for i in range(n_rows)])

        if dtype == "integer":
            mn, mx = spec.get("min", 0), spec.get("max", 100)
            return pl.Series(name, np.random.randint(mn, max(mx + 1, mn + 1), size=n_rows).tolist())

        if dtype == "float":
            mn, mx = spec.get("min", 0.0), spec.get("max", 1.0)
            if mn == mx:
                mx = mn + 1.0
            return pl.Series(name, np.random.uniform(mn, mx, size=n_rows).tolist())

        if dtype == "boolean":
            return pl.Series(name, np.random.choice([True, False], size=n_rows).tolist())

        # categorical or string
        vals = spec.get("values") or ["value_A", "value_B", "value_C"]
        return pl.Series(name, np.random.choice(vals, size=n_rows).tolist())

    # ------------------------------------------------------------------
    # Internal: error injection (stress_test mode only)
    # ------------------------------------------------------------------

    def _apply_error_injection(
        self, df: pl.DataFrame, config: dict, pk_col: Optional[str]
    ) -> pl.DataFrame:
        ei = config.get("error_injection", {})
        n = df.height

        # missing_values
        mv = ei.get("missing_values", {})
        if mv.get("rate", 0.0) > 0:
            target_cols = mv.get("columns") or [c for c in df.columns if c != pk_col]
            for col in target_cols:
                if col in df.columns:
                    mask = pl.Series(np.random.rand(n) < mv["rate"])
                    df = df.with_columns(
                        pl.when(mask).then(None).otherwise(pl.col(col)).alias(col)
                    )

        # wrong_type — cast numeric columns to Utf8 and inject "ERROR" at stated rate
        wt = ei.get("wrong_type", {})
        if wt.get("rate", 0.0) > 0:
            rate = wt["rate"]
            target_cols = wt.get("columns") or [
                c["name"] for c in config["columns"]
                if c.get("dtype") in ("float", "integer") and c["name"] != pk_col
            ]
            for col in target_cols:
                if col in df.columns:
                    mask = np.random.rand(n) < rate
                    str_vals = df[col].cast(pl.Utf8).to_list()
                    for i, inject in enumerate(mask):
                        if inject:
                            str_vals[i] = "ERROR"
                    df = df.with_columns(pl.Series(col, str_vals))

        # duplicate_ids — build PK column with exactly round(rate*n) duplicated entries
        di = ei.get("duplicate_ids", {})
        if di.get("rate", 0.0) > 0 and pk_col and pk_col in df.columns:
            rate = di["rate"]
            n_dups = max(1, round(rate * n))
            n_unique = n - n_dups
            unique_vals = [f"{pk_col}_{i:06d}" for i in range(n_unique)]
            dup_vals = [random.choice(unique_vals) for _ in range(n_dups)]
            all_vals = unique_vals + dup_vals
            random.shuffle(all_vals)
            df = df.with_columns(pl.Series(pk_col, all_vals))

        # pk_mismatches — replace rate fraction of PK values with orphan IDs
        pm = ei.get("pk_mismatches", {})
        if pm.get("rate", 0.0) > 0 and pk_col and pk_col in df.columns:
            rate = pm["rate"]
            n_mis = max(1, round(rate * n))
            pk_vals = df[pk_col].to_list()
            mis_targets = np.random.choice(n, size=n_mis, replace=False)
            for j, tgt in enumerate(mis_targets):
                pk_vals[int(tgt)] = f"ORPHAN_{j:08d}"
            df = df.with_columns(pl.Series(pk_col, pk_vals))

        # schema_errors — append an unexpected column to signal schema corruption
        se = ei.get("schema_errors", {})
        if se.get("rate", 0.0) > 0:
            df = df.with_columns(pl.lit("UNEXPECTED_VALUE").alias("EXTRA_COL_DO_NOT_USE"))

        # malformed_fields — inject garbled strings into string/categorical columns
        mf = ei.get("malformed_fields", {})
        if mf.get("rate", 0.0) > 0:
            rate = mf["rate"]
            target_cols = mf.get("columns") or [
                c["name"] for c in config["columns"]
                if c.get("dtype") in ("string", "categorical") and c["name"] != pk_col
            ]
            for col in target_cols:
                if col in df.columns:
                    mask = np.random.rand(n) < rate
                    str_vals = [str(v) if v is not None else None for v in df[col].to_list()]
                    for i, inject in enumerate(mask):
                        if inject:
                            str_vals[i] = random.choice(_MALFORMED_STRINGS)
                    df = df.with_columns(pl.Series(col, str_vals))

        return df


# ===========================================================================
# Module-level helpers (retained for backward compatibility)
# ===========================================================================

def clean_header(col_name: str) -> str:
    """Sanitizes a messy TSV column header into a safe, snake_case name."""
    s = str(col_name).lower()
    s = re.sub(r'[/.:\s\-]+', '_', s)
    s = re.sub(r'[^\w_]', '', s)
    s = re.sub(r'_+', '_', s)
    return s.strip('_')


def generate_fake_column(series: pl.Series, n_rows: int) -> pl.Series:
    """Generates synthetic data matching the type and distribution of a polars series."""
    dtype = series.dtype
    if dtype in [pl.Int32, pl.Int64]:
        min_val, max_val = series.min(), series.max()
        return pl.Series(series.name, np.random.randint(min_val or 0, (max_val or 100) + 1, size=n_rows))
    elif dtype in [pl.Float32, pl.Float64]:
        min_val, max_val = series.min(), series.max()
        return pl.Series(series.name, np.random.uniform(min_val or 0.0, max_val or 1.0, size=n_rows))
    elif dtype in [pl.Date, pl.Datetime]:
        min_val, max_val = series.min(), series.max()
        if min_val is None or max_val is None:
            return pl.Series(series.name, [None] * n_rows)
        min_ts = int(min_val.strftime("%s")) if hasattr(min_val, 'strftime') else min_val
        max_ts = int(max_val.strftime("%s")) if hasattr(max_val, 'strftime') else max_val
        random_timestamps = np.random.randint(min_ts, max_ts + 1, size=n_rows)
        if dtype == pl.Date:
            return pl.Series(series.name, [datetime.fromtimestamp(ts).date() for ts in random_timestamps])
        else:
            return pl.Series(series.name, [datetime.fromtimestamp(ts) for ts in random_timestamps])
    elif dtype in [pl.Boolean]:
        return pl.Series(series.name, np.random.choice([True, False], size=n_rows))
    else:
        unique_vals = series.drop_nulls().unique().to_list()
        if not unique_vals:
            unique_vals = ["unknown"]
        return pl.Series(series.name, np.random.choice(unique_vals, size=n_rows))


def introduce_missing_values(df: pl.DataFrame, missing_fraction=0.1) -> pl.DataFrame:
    """Randomly injects null values and messy strings into the dataframe."""
    exprs = []
    messy_strings = [None, "-", "unknown", "N/A", "not found", "None", ""]
    for col in df.columns:
        series = df[col]
        dtype = series.dtype
        mask = pl.Series(np.random.rand(df.height) < missing_fraction)
        if dtype in [pl.Categorical, pl.String, pl.Utf8]:
            random_messy = pl.Series(np.random.choice(messy_strings, size=df.height))
            expr = pl.when(mask).then(random_messy).otherwise(pl.col(col)).alias(col)
        else:
            expr = pl.when(mask).then(None).otherwise(pl.col(col)).alias(col)
        exprs.append(expr)
    return df.with_columns(exprs)


def main():
    parser = argparse.ArgumentParser(
        description=(
            "AquaSynthesizer: two-step synthetic data generator. "
            "Use AquaSynthesizer().propose_config(source) + .generate(config) for the new API."
        )
    )
    parser.add_argument("--generate_only", nargs='+', help="Quick generate mode: provide headers as list")
    parser.add_argument("--n_rows", type=int, default=50, help="Number of rows for quick generate")
    parser.add_argument("--data_dir", help="Path to directory containing real data.")
    parser.add_argument("--data_files", nargs='+', help="Specific data file(s).")
    parser.add_argument("--metadata_file", help="Path to real metadata file.")
    parser.add_argument("--primary_key_data", nargs='+', help="Primary key column(s) in data files.")
    parser.add_argument("--primary_key_metadata", help="Primary key in metadata.")
    parser.add_argument("--output_primary_key", help="Standardized output PK name.")
    parser.add_argument("--mismatches", action="store_true", help="Inject PK mismatches.")
    parser.add_argument("--duplicates", action="store_true", help="Inject PK duplicates.")
    parser.add_argument("--missing_values", action="store_true", help="Inject nulls.")
    parser.add_argument("--out_dir", default=".", help="Output directory.")

    args = parser.parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    if args.generate_only:
        headers = args.generate_only
        n = args.n_rows
        target_file = out_dir / f"synthetic_gen_{timestamp}.tsv"
        with open(target_file, "w") as f:
            f.write("\t".join(headers) + "\n")
            for i in range(n):
                row_vals = []
                for h in headers:
                    if "id" in h.lower() or "pk" in h.lower():
                        row_vals.append(f"REC_{i}")
                    else:
                        row_vals.append(f"value_{i}")
                f.write("\t".join(row_vals) + "\n")
        print(f"Generated {n} records to {target_file}")
        return

    if not (args.data_files or args.data_dir):
        if not any(vars(args).values()):
            parser.print_help()
        return

    all_data_files = []
    if args.data_dir:
        dpath = Path(args.data_dir)
        if args.data_files:
            for f_name in args.data_files:
                all_data_files.append(str(dpath / f_name))
        else:
            found_files = list(dpath.glob("*.tsv")) + list(dpath.glob("*.csv"))
            all_data_files.extend([str(p) for p in found_files])
    elif args.data_files:
        all_data_files.extend(args.data_files)

    global_keys: set = set()
    data_dfs = []
    for d_file in all_data_files:
        if not Path(d_file).exists():
            continue
        df = pl.read_csv(d_file, separator='\t' if d_file.endswith('.tsv') else ',')
        actual_key = next((k for k in (args.primary_key_data or []) if k in df.columns), None)
        data_dfs.append((Path(d_file), df, actual_key))
        if actual_key:
            global_keys.update(df[actual_key].drop_nulls().to_list())

    if not global_keys and data_dfs:
        n_rows_sum = sum(df.height for _, df, _ in data_dfs)
        global_keys.update([str(x) for x in range(n_rows_sum)])

    n_unique_keys = len(global_keys)
    fake_ids_ints = random.sample(range(10000000, 99999999), n_unique_keys)
    id_map = dict(zip(global_keys, [str(x) for x in fake_ids_ints]))

    for filepath, df_real, actual_key in data_dfs:
        n_rows = df_real.height
        file_ids = [id_map.get(x, str(random.randint(10000000, 99999999))) for x in (
            df_real[actual_key].to_list() if actual_key else range(n_rows))]
        target_key_name = args.output_primary_key or actual_key or "id"
        fake_data_cols = []
        for col in df_real.columns:
            if col == actual_key:
                fake_data_cols.append(pl.Series(target_key_name, file_ids))
            else:
                fake_data_cols.append(generate_fake_column(df_real[col], n_rows).alias(clean_header(col)))
        df_fake = pl.DataFrame(fake_data_cols)
        if args.missing_values:
            df_fake = introduce_missing_values(df_fake, 0.05)
        out_path = out_dir / f"test_data_{filepath.stem}_{timestamp}.tsv"
        df_fake.write_csv(out_path, separator='\t')
        print(f"Created: {out_path}")


if __name__ == "__main__":
    main()
